import json
import zipfile
import uuid
from datetime import datetime, timezone
from pathlib import Path

from app.models.export import ExportFile, ExportManifest
from app.models.job import Job
from app.services.project_context import PROJECT_ROOT, get_export_packages_dir, get_export_jobs_dir


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _packages_dir() -> Path:
    d = get_export_packages_dir()
    d.mkdir(parents=True, exist_ok=True)
    return d


def _index_file(job_id: str) -> Path:
    return get_export_jobs_dir() / job_id / "exports_index.json"


def _load_index(job_id: str) -> list[str]:
    f = _index_file(job_id)
    if not f.exists():
        return []
    try:
        return json.loads(f.read_text(encoding="utf-8"))
    except Exception:
        return []


def _save_index(job_id: str, ids: list[str]) -> None:
    f = _index_file(job_id)
    f.parent.mkdir(parents=True, exist_ok=True)
    f.write_text(json.dumps(ids, indent=2), encoding="utf-8")


def _manifest_path(export_id: str) -> Path:
    return _packages_dir() / export_id / "export_manifest.json"


def _load_manifest(export_id: str) -> ExportManifest | None:
    p = _manifest_path(export_id)
    if not p.exists():
        return None
    try:
        return ExportManifest.model_validate_json(p.read_text(encoding="utf-8"))
    except Exception:
        return None


def create_export(job: Job) -> ExportManifest:
    from app.services.credit_service import spend_credits, get_pricing
    pricing = get_pricing()
    spend_credits(pricing.export_cost, "exports", "create_export", "Create Export Package")

    export_id = str(uuid.uuid4())
    now = _now()
    package_dir = _packages_dir() / export_id
    package_dir.mkdir(parents=True, exist_ok=True)

    readme_path = package_dir / "README.txt"
    readme_path.write_text(
        f"MiniMesh Export Package\n"
        f"=======================\n"
        f"Export ID  : {export_id}\n"
        f"Job ID     : {job.id}\n"
        f"Provider   : {job.provider}\n"
        f"Mode       : {job.mode}\n"
        f"Created    : {now}\n\n"
        f"This is a placeholder export package generated by MiniMesh Phase 6.\n"
        f"Real mesh exports (GLB, GLTF, OBJ, FBX) will be connected in future phases.\n",
        encoding="utf-8",
    )

    manifest_json_path = package_dir / "manifest.json"
    manifest_json_path.write_text(
        json.dumps(
            {
                "job_id": job.id,
                "export_id": export_id,
                "provider": job.provider,
                "export_type": "preview_package",
                "outputs": [],
                "note": "Placeholder package â€” no real mesh outputs yet.",
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    zip_path = package_dir / "bundle.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.write(readme_path, "README.txt")
        zf.write(manifest_json_path, "manifest.json")

    files: list[ExportFile] = [
        ExportFile(
            filename=readme_path.name,
            path=str(readme_path.relative_to(PROJECT_ROOT)),
            type="readme",
            size=readme_path.stat().st_size,
            created_at=now,
        ),
        ExportFile(
            filename=manifest_json_path.name,
            path=str(manifest_json_path.relative_to(PROJECT_ROOT)),
            type="manifest",
            size=manifest_json_path.stat().st_size,
            created_at=now,
        ),
        ExportFile(
            filename=zip_path.name,
            path=str(zip_path.relative_to(PROJECT_ROOT)),
            type="zip_bundle",
            size=zip_path.stat().st_size,
            created_at=now,
        ),
    ]

    manifest = ExportManifest(
        job_id=job.id,
        export_id=export_id,
        provider=job.provider,
        mode=job.mode,
        export_type="preview_package",
        files=files,
        created_at=now,
    )
    _manifest_path(export_id).write_text(manifest.model_dump_json(indent=2), encoding="utf-8")

    index = _load_index(job.id)
    index.append(export_id)
    _save_index(job.id, index)

    return manifest


def get_export(export_id: str) -> ExportManifest | None:
    return _load_manifest(export_id)


def list_exports_for_job(job_id: str) -> list[ExportManifest]:
    return [m for eid in _load_index(job_id) if (m := _load_manifest(eid))]


def get_zip_path(export_id: str) -> Path | None:
    p = _packages_dir() / export_id / "bundle.zip"
    return p if p.exists() else None
